# TCL File Generated by Component Editor 18.1
# Wed Sep 03 19:44:14 GMT-03:00 2025
# DO NOT MODIFY


# 
# codec_pus_v01 "codec_pus_v01" v0.1
#  2025.09.03.19:44:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module codec_pus_v01
# 
set_module_property DESCRIPTION ""
set_module_property NAME codec_pus_v01
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME codec_pus_v01
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL codec_PUS_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file codec_PUS_Avalon_Read.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_Avalon_Read/codec_PUS_Avalon_Read.vhd
add_fileset_file codec_PUS_Avalon_Write.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_Avalon_Write/codec_PUS_Avalon_Write.vhd
add_fileset_file codec_PUS_Receiver_Transmitter_CCSDS_in_wAvalon.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_CCSDS_in_wAvalon/codec_PUS_Receiver_Transmitter_CCSDS_in_wAvalon.vhd
add_fileset_file codec_PUS_Receiver_Transmitter_CCSDS_out.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_CCSDS_out/codec_PUS_Receiver_Transmitter_CCSDS_out.vhd
add_fileset_file codec_PUS_CRC16CITT_Module.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_CRC16CITT_Module/codec_PUS_CRC16CITT_Module.vhd
add_fileset_file codec_PUS_Input_Header_FIFO.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_Input_Header_FIFO/codec_PUS_Input_Header_FIFO.vhd
add_fileset_file codec_PUS_IRQ_Controller.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_IRQ_Controller/codec_PUS_IRQ_Controller.vhd
add_fileset_file codec_PUS_Output_Header_FIFO.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_Output_Header_FIFO/codec_PUS_Output_Header_FIFO.vhd
add_fileset_file codec_PUS_Registers_Controller_Module.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_Registers_Controller_Module/codec_PUS_Registers_Controller_Module.vhd
add_fileset_file codec_PUS_main_pkg.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_main_pkg.vhd
add_fileset_file codec_PUS_top.vhd VHDL PATH ../../../EnVision_Simulator_PUS_Codec/Development/FPGA_Development/codec_PUS_top.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 100
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point avalon_agent
# 
add_interface avalon_agent avalon end
set_interface_property avalon_agent addressUnits WORDS
set_interface_property avalon_agent associatedClock clock_sink
set_interface_property avalon_agent associatedReset reset_sink
set_interface_property avalon_agent bitsPerSymbol 8
set_interface_property avalon_agent burstOnBurstBoundariesOnly false
set_interface_property avalon_agent burstcountUnits WORDS
set_interface_property avalon_agent explicitAddressSpan 0
set_interface_property avalon_agent holdTime 0
set_interface_property avalon_agent linewrapBursts false
set_interface_property avalon_agent maximumPendingReadTransactions 0
set_interface_property avalon_agent maximumPendingWriteTransactions 0
set_interface_property avalon_agent readLatency 0
set_interface_property avalon_agent readWaitTime 1
set_interface_property avalon_agent setupTime 0
set_interface_property avalon_agent timingUnits Cycles
set_interface_property avalon_agent writeWaitTime 0
set_interface_property avalon_agent ENABLED true
set_interface_property avalon_agent EXPORT_OF ""
set_interface_property avalon_agent PORT_NAME_MAP ""
set_interface_property avalon_agent CMSIS_SVD_VARIABLES ""
set_interface_property avalon_agent SVD_ADDRESS_GROUP ""

add_interface_port avalon_agent avalon_mm_agent_addr_i address Input 5
add_interface_port avalon_agent avalon_mm_agent_write_data_i writedata Input 32
add_interface_port avalon_agent avalon_mm_agent_read_i read Input 1
add_interface_port avalon_agent avalon_mm_agent_write_i write Input 1
add_interface_port avalon_agent avalon_mm_agent_wait_request_o waitrequest Output 1
add_interface_port avalon_agent avalon_mm_agent_read_data_o readdata Output 32
set_interface_assignment avalon_agent embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_agent embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_agent embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_agent embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avalon_mm_master_wait_request_i waitrequest Input 1
add_interface_port avalon_master avalon_mm_master_read_data_i readdata Input 32
add_interface_port avalon_master avalon_mm_master_addr_o address Output 32
add_interface_port avalon_master avalon_mm_master_write_data_o writedata Output 32
add_interface_port avalon_master avalon_mm_master_read_o read Output 1
add_interface_port avalon_master avalon_mm_master_write_o write Output 1


# 
# connection point IRQ_sender_recv
# 
add_interface IRQ_sender_recv interrupt end
set_interface_property IRQ_sender_recv associatedAddressablePoint ""
set_interface_property IRQ_sender_recv associatedClock clock_sink
set_interface_property IRQ_sender_recv associatedReset reset_sink
set_interface_property IRQ_sender_recv bridgedReceiverOffset ""
set_interface_property IRQ_sender_recv bridgesToReceiver ""
set_interface_property IRQ_sender_recv ENABLED true
set_interface_property IRQ_sender_recv EXPORT_OF ""
set_interface_property IRQ_sender_recv PORT_NAME_MAP ""
set_interface_property IRQ_sender_recv CMSIS_SVD_VARIABLES ""
set_interface_property IRQ_sender_recv SVD_ADDRESS_GROUP ""

add_interface_port IRQ_sender_recv IRQ_send_recv_o irq Output 1


# 
# connection point IRQ_sender_send
# 
add_interface IRQ_sender_send interrupt end
set_interface_property IRQ_sender_send associatedAddressablePoint ""
set_interface_property IRQ_sender_send associatedClock clock_sink
set_interface_property IRQ_sender_send associatedReset reset_sink
set_interface_property IRQ_sender_send bridgedReceiverOffset ""
set_interface_property IRQ_sender_send bridgesToReceiver ""
set_interface_property IRQ_sender_send ENABLED true
set_interface_property IRQ_sender_send EXPORT_OF ""
set_interface_property IRQ_sender_send PORT_NAME_MAP ""
set_interface_property IRQ_sender_send CMSIS_SVD_VARIABLES ""
set_interface_property IRQ_sender_send SVD_ADDRESS_GROUP ""

add_interface_port IRQ_sender_send IRQ_send_send_o irq Output 1


# 
# connection point conduit_spw_interface
# 
add_interface conduit_spw_interface conduit end
set_interface_property conduit_spw_interface associatedClock clock_sink
set_interface_property conduit_spw_interface associatedReset reset_sink
set_interface_property conduit_spw_interface ENABLED true
set_interface_property conduit_spw_interface EXPORT_OF ""
set_interface_property conduit_spw_interface PORT_NAME_MAP ""
set_interface_property conduit_spw_interface CMSIS_SVD_VARIABLES ""
set_interface_property conduit_spw_interface SVD_ADDRESS_GROUP ""

add_interface_port conduit_spw_interface conduit_inFIFO_data_i conduit_infifo_data_signal Input 8
add_interface_port conduit_spw_interface conduit_inFIFO_flag_i conduit_infifo_flag_signal Input 1
add_interface_port conduit_spw_interface conduit_inFIFO_almost_empty_i conduit_infifo_almost_empty_signal Input 1
add_interface_port conduit_spw_interface conduit_inFIFO_empty_i conduit_infifo_empty_signal Input 1
add_interface_port conduit_spw_interface conduit_inFIFO_rxvalid_i conduit_infifo_rxvalid_signal Input 1
add_interface_port conduit_spw_interface conduit_outFIFO_almost_full_i conduit_outfifo_almost_full_signal Input 1
add_interface_port conduit_spw_interface conduit_outFIFO_full_i conduit_outfifo_full_signal Input 1
add_interface_port conduit_spw_interface conduit_outFIFO_txrdy_i conduit_outfifo_txrdy_signal Input 1
add_interface_port conduit_spw_interface conduit_outFIFO_data_o conduit_outfifo_data_signal Output 8
add_interface_port conduit_spw_interface conduit_inFIFO_rd_en_o conduit_infifo_rd_en_signal Output 1
add_interface_port conduit_spw_interface conduit_outFIFO_flag_o conduit_outfifo_flag_signal Output 1
add_interface_port conduit_spw_interface conduit_outFIFO_wr_en_o conduit_outfifo_wr_en_signal Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_sync_i reset Input 1

